[package]
name = "ootrstats-worker-windows-service-uninstaller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
eventlog = "0.4"
thiserror = "2"
windows-service = "0.8"
windows-sys = { version = "0.61", features = ["Win32"] }
